version: '3.9'
services:
  express:
    container_name: express
    restart: unless-stopped
    ports:
      - '3003:3003'
    volumes:
      - ./express:/src
      - /src/node_modules
    build:
      context: ./express/
    command: npm run dev
  